name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: harivansh-afk
          template: classic
          base: header
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  acti_comm:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: harivansh-afk
          template: classic
          base: activity
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  iso_calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: harivansh-afk
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

